using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Text.Json;
using System.Windows.Forms;
using System.Drawing.Drawing2D;
using System.Drawing.Text;

namespace SimpleBrightness
{
    public class HelpForm : Form { public HelpForm() { this.Text = "关于 & 说明"; this.Size = new Size(520, 480); this.StartPosition = FormStartPosition.CenterScreen; this.FormBorderStyle = FormBorderStyle.FixedDialog; this.MaximizeBox = false; this.MinimizeBox = false; this.BackColor = Color.FromArgb(31, 31, 31); this.ForeColor = Color.White; Label title = new Label { Text = "HM's Simple Brightness Tool", Top = 20, Left = 20, AutoSize = true, Font = new Font("Segoe UI", 14, FontStyle.Bold) }; TextBox info = new TextBox { Multiline = true, ReadOnly = true, ScrollBars = ScrollBars.Vertical, Top = 60, Left = 20, Width = 460, Height = 320, BackColor = Color.FromArgb(45, 45, 45), ForeColor = Color.LightGray, BorderStyle = BorderStyle.None, Font = new Font("Segoe UI", 9), Text = @"HM's Simple Brightness Tool" + Environment.NewLine + Environment.NewLine + @"一个极致轻量、便携、现代化的 Windows 屏幕亮度控制工具。" + Environment.NewLine + @"(用不惯Twinkle Tray，软件体积大，卡，提交issue也得不到支持。故自己搓一个适合自己体制的程序)" + Environment.NewLine + Environment.NewLine + @"【核心功能】" + Environment.NewLine + @"1. 极速调节：鼠标悬停任务栏托盘图标，滚动滚轮即可调节。" + Environment.NewLine + @"   (移出图标区域调节立即停止，防止误触)" + Environment.NewLine + @"2. 中键同步：对着托盘图标点击【中键】，强制将所有屏幕亮度同步为主屏数值。" + Environment.NewLine + Environment.NewLine + @"【独家：非线性曲线】" + Environment.NewLine + @"在控制中心点击“编辑曲线”，可自定义亮度映射。" + Environment.NewLine + @"解决副屏“调到10%太暗，调到20%又太亮”的问题。" + Environment.NewLine + @"示例：设置软件50%对应硬件20%，实现极致微调。" + Environment.NewLine + Environment.NewLine + @"【设置说明】" + Environment.NewLine + @"- 调节响应延迟：针对老旧显示器，调高此值可防止卡顿丢包（防抖动）。" + Environment.NewLine + @"- 电源按钮模式：" + Environment.NewLine + @"  DDC/CI：硬件指令，彻底断电（部分显示器唤不醒）。" + Environment.NewLine + @"  Windows API：软件黑屏信号，兼容性最好（推荐笔记本外接使用）。" }; info.SelectionLength = 0; Button btnOk = new Button { Text = "关闭", Top = 400, Left = 380, Width = 100, Height = 35, BackColor = Color.Teal, ForeColor = Color.White, FlatStyle = FlatStyle.Flat, DialogResult = DialogResult.OK }; this.Controls.Add(title); this.Controls.Add(info); this.Controls.Add(btnOk); } }
    public class InputBox : Form { public string ResultText { get; private set; } = ""; public InputBox(string title, string prompt, string defaultText) { this.Size = new Size(300, 180); this.Text = title; this.StartPosition = FormStartPosition.CenterScreen; this.FormBorderStyle = FormBorderStyle.FixedDialog; Label l = new Label { Text = prompt, Top = 20, Left = 20, AutoSize = true }; TextBox t = new TextBox { Text = defaultText, Top = 50, Left = 20, Width = 240 }; Button b = new Button { Text = "确定", Top = 90, Left = 180, DialogResult = DialogResult.OK }; b.Click += (s, e) => { ResultText = t.Text; this.Close(); }; this.Controls.AddRange(new Control[] { l, t, b }); this.AcceptButton = b; } }
    public class AppConfig { public int ScrollStep { get; set; } = 5; public int DebounceTime { get; set; } = 200; public bool UseSoftwarePower { get; set; } = false; public List<string> HiddenMonitors { get; set; } = new List<string>(); public Dictionary<string, string> CustomNames { get; set; } = new Dictionary<string, string>(); public Dictionary<string, Dictionary<int, int>> Curves { get; set; } = new Dictionary<string, Dictionary<int, int>>(); public Dictionary<string, int> SavedBrightness { get; set; } = new Dictionary<string, int>(); private static string ConfigPath = Path.Combine(Application.StartupPath, "HMSimpleBrightness_Config.json"); public static AppConfig Load() { if (File.Exists(ConfigPath)) { try { return JsonSerializer.Deserialize<AppConfig>(File.ReadAllText(ConfigPath)) ?? new AppConfig(); } catch { } } return new AppConfig(); } public void Save() { try { File.WriteAllText(ConfigPath, JsonSerializer.Serialize(this)); } catch { } } public Dictionary<int, int> GetCurveForMonitor(string id) { if (Curves.ContainsKey(id)) return Curves[id]; return new Dictionary<int, int> { { 0, 0 }, { 100, 100 } }; } }
    public class MonitorInfo { public string Name { get; set; } = "Unknown"; public MonitorType Type { get; set; } public IntPtr Handle { get; set; } public string InstanceId { get; set; } = ""; public string UniqueId { get; set; } = ""; public int LastBrightness { get; set; } = 50; }
    public enum MonitorType { WMI, DDC }
}
